"""
Write tools/logic_tests/Generated/AileronMetrics.cs: Aileron advance widths for fit tests outside Unity.

DESIGN_SPEC.md §2.5: `AileronMetrics.Width(string text, string weight, float sizeU)` sums the advance
widths (UPM 1000, no kerning, the same method the spec's measurements used) of every character for the
SemiBold, Bold or Black weight and scales them to `sizeU` canvas units. A character the font does not
map throws, so a test can never pass on a glyph that would render as a box.

The advance widths are read from the staged OpenType files (the TrueType files made by
tools/convert_fonts.py keep the same `hmtx`), or from any folder holding Aileron-<Weight>.otf/.ttf.

Usage:
    python tools/make_font_metrics.py [--src <dir>] [--out <file>]
    python tools/make_font_metrics.py --measure "Today from R9 999" SemiBold 32
"""
import argparse
import os
import sys

from fontTools.ttLib import TTFont

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SRC = os.path.join(r"C:\Temp\MaliGoAssetsStaging", "dotcolon_aileron")
DEFAULT_OUT = os.path.join(REPO_ROOT, "tools", "logic_tests", "Generated", "AileronMetrics.cs")
WEIGHTS = ("SemiBold", "Bold", "Black")


def load_advances(src, weight):
    for ext in (".otf", ".ttf"):
        path = os.path.join(src, "Aileron-%s%s" % (weight, ext))
        if os.path.isfile(path):
            font = TTFont(path)
            upm = font["head"].unitsPerEm
            if upm != 1000:
                raise SystemExit("%s: unitsPerEm %d, expected 1000" % (path, upm))
            hmtx = font["hmtx"]
            return {code: hmtx[name][0] for code, name in font.getBestCmap().items()}, path
    raise SystemExit("MISSING Aileron-%s.otf/.ttf in %s" % (weight, src))


def width(advances, text, size):
    total = 0
    for ch in text:
        if ord(ch) not in advances:
            raise KeyError("U+%04X %r is not in the font" % (ord(ch), ch))
        total += advances[ord(ch)]
    return total * size / 1000.0


def cs_char(code):
    return "\\u%04X" % code


def generate(tables, sources):
    codes = sorted(tables[WEIGHTS[0]].keys())
    for weight in WEIGHTS[1:]:
        if sorted(tables[weight].keys()) != codes:
            raise SystemExit("cmap differs between weights; the generator assumes one character set")
    if any(code > 0xFFFF for code in codes):
        raise SystemExit("non-BMP code point in cmap; extend the generator")

    lines = []
    out = lines.append
    out("// <auto-generated>")
    out("// Written by tools/make_font_metrics.py from %s." % ", ".join(sorted(sources)))
    out("// Do not edit by hand: re-run the script. Aileron is CC0 (Assets/MaliGo/Licenses/Aileron-License.txt).")
    out("// </auto-generated>")
    out("using System;")
    out("using System.Collections.Generic;")
    out("")
    out("/// <summary>")
    out("/// Aileron advance widths (units per em 1000, no kerning) for copy-fit tests outside Unity (DESIGN_SPEC §2.5).")
    out("/// </summary>")
    out("public static class AileronMetrics")
    out("{")
    out("    public const int UnitsPerEm = 1000;")
    out("")
    out("    /// <summary>Every character the three weights map (%d, identical in each weight).</summary>" % len(codes))
    chunks = []
    row = []
    for i, code in enumerate(codes):
        row.append(cs_char(code))
        if len(row) == 16 or i == len(codes) - 1:
            chunks.append('        "%s"' % "".join(row))
            row = []
    out("    const string Characters =")
    out(" +\n".join(chunks) + ";")
    for weight in WEIGHTS:
        values = [str(tables[weight][code]) for code in codes]
        out("")
        out("    static readonly int[] %sAdvances =" % weight)
        out("    {")
        for start in range(0, len(values), 20):
            out("        " + ", ".join(values[start:start + 20]) + ",")
        out("    };")
    out("")
    out("    static Dictionary<char, int> semiBold, bold, black;")
    out("")
    out("    /// <summary>Width in canvas units of <paramref name=\"text\"/> set in Aileron <paramref name=\"weight\"/>")
    out("    /// (\"SemiBold\", \"Bold\" or \"Black\", any case) at <paramref name=\"sizeU\"/> units. A character the font")
    out("    /// does not map throws.</summary>")
    out("    public static float Width(string text, string weight, float sizeU)")
    out("    {")
    out("        if (text == null) throw new ArgumentNullException(nameof(text));")
    out("        Dictionary<char, int> table = Table(weight);")
    out("        long total = 0;")
    out("        foreach (char c in text)")
    out("        {")
    out("            if (!table.TryGetValue(c, out int advance))")
    out("                throw new ArgumentException(\"Aileron has no glyph for U+\" + ((int)c).ToString(\"X4\") + \" in \\\"\" + text + \"\\\"\");")
    out("            total += advance;")
    out("        }")
    out("        return total * sizeU / UnitsPerEm;")
    out("    }")
    out("")
    out("    /// <summary>True when Aileron maps <paramref name=\"c\"/> (every weight has the same set).</summary>")
    out("    public static bool Has(char c) => Table(\"Bold\").ContainsKey(c);")
    out("")
    out("    static Dictionary<char, int> Table(string weight)")
    out("    {")
    out("        switch ((weight ?? string.Empty).ToLowerInvariant())")
    out("        {")
    out("            case \"semibold\": return semiBold ?? (semiBold = Build(SemiBoldAdvances));")
    out("            case \"bold\": return bold ?? (bold = Build(BoldAdvances));")
    out("            case \"black\": return black ?? (black = Build(BlackAdvances));")
    out("            default: throw new ArgumentException(\"Unknown Aileron weight '\" + weight + \"' (SemiBold, Bold or Black)\");")
    out("        }")
    out("    }")
    out("")
    out("    static Dictionary<char, int> Build(int[] advances)")
    out("    {")
    out("        var table = new Dictionary<char, int>(Characters.Length);")
    out("        for (int i = 0; i < Characters.Length; i++) table[Characters[i]] = advances[i];")
    out("        return table;")
    out("    }")
    out("}")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--src", default=DEFAULT_SRC)
    parser.add_argument("--out", default=DEFAULT_OUT)
    parser.add_argument("--measure", nargs=3, metavar=("TEXT", "WEIGHT", "SIZE"),
                        help="print one width instead of writing the file")
    args = parser.parse_args()

    tables, sources = {}, []
    for weight in WEIGHTS:
        tables[weight], path = load_advances(args.src, weight)
        sources.append(os.path.basename(path))

    if args.measure:
        text, weight, size = args.measure
        print("%.1f u" % width(tables[weight], text, float(size)))
        return 0

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write(generate(tables, sources))
    print("wrote %s (%d characters x %d weights)" % (os.path.relpath(args.out, REPO_ROOT), len(tables["Bold"]), len(WEIGHTS)))
    # Spot checks against numbers quoted in DESIGN_SPEC §5.4.1.
    for text, weight, size, quoted in (("Today from R9 999", "SemiBold", 32, 279), ("Day 3 of 7", "Bold", 40, 185),
                                       ("R1 315", "Black", 44, 154), ("Speaker owed", "Bold", 36, 244)):
        print("  %-20s %-8s %3d -> %6.1f u (spec %d)" % (text, weight, size, width(tables[weight], text, size), quoted))
    return 0


if __name__ == "__main__":
    sys.exit(main())
